// <auto-generated />
using System;
using Grades.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grades.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240228231117_student2")]
    partial class student2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grades.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            Abbreviation = "A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "42c0865f-f405-44ad-9028-68cfa6589b44",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED00Oqyv+6+/jE2oUrXhZtXvlnZQ1B4+AN/5OKIqlyInVTbe1EXbHbSmAGEsMwGy+Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "eaf3beb6-878a-4fb2-9b5b-076cfae88836",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Abbreviation = "EC",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "29f91421-700d-49d2-9447-622bf56585c3",
                            Email = "economy@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Economy Faculty",
                            NormalizedEmail = "ECONOMY@GMAIL.COM",
                            NormalizedUserName = "ECONOMY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENU0qMFLPvYfMyh5OFPy3KFRXaFshG+pPq4m23O9B4CTwH44MYm7rNy+BsiVPQjTMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "617c21b4-c469-4158-bc04-3f6e5cf74201",
                            TwoFactorEnabled = false,
                            UserName = "economy@gmail.com"
                        },
                        new
                        {
                            Id = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            Abbreviation = "LF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "96a6df39-4de3-442a-b8ac-323dc4f861d6",
                            Email = "law@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Law Faculty",
                            NormalizedEmail = "LAW@GMAIL.COM",
                            NormalizedUserName = "LAW@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBQm0B23QYrghTIJhBugNkX4Lo7cFUKs5XeUBWbcwztMBBXH5WkxuA/Z8yCqVprJtQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc573d0f-40fc-4d55-b607-58c989a5980d",
                            TwoFactorEnabled = false,
                            UserName = "law@gmail.com"
                        },
                        new
                        {
                            Id = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            Abbreviation = "U",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "79ae9788-825b-4eb8-8be4-91c7d088de15",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELZtOolt0MhiMQwY9U3AnAn18ANgyoAB6m8K3c+EYL5p77BGwChmATju9QjpEhEEXw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b952364-de1d-4751-b719-74dfd7f21539",
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b93ac11f-e410-4e93-8291-c19be7ac5993"),
                            Abbreviation = "F1",
                            DefaultValue = false,
                            Name = "Faculty 1"
                        },
                        new
                        {
                            Id = new Guid("b9e7343e-a7fa-475e-8b9a-14f191c8e70e"),
                            Abbreviation = "F2",
                            DefaultValue = false,
                            Name = "Faculty 2"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2d78dc28-25c1-4e52-a08d-5a78a8f81c5d"),
                            AdmissionYear = 2021,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 1
                        },
                        new
                        {
                            Id = new Guid("69f6d9a2-3a21-48f0-aa59-2bc982b367c3"),
                            AdmissionYear = 2020,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "ЕК",
                            SpecialtyId = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            SubgroupNumber = 2
                        },
                        new
                        {
                            Id = new Guid("4c09d510-2ef3-417a-b36a-41b82d39b159"),
                            AdmissionYear = 2022,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 2
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            Code = "122",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Комп'ютерні науки"
                        },
                        new
                        {
                            Id = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            Code = "051",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Економіка"
                        },
                        new
                        {
                            Id = new Guid("b6d2cb2f-8c5a-4ff4-98b2-728c3d0f2c8e"),
                            Code = "075",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Маркетинг"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AverageGrade")
                        .HasColumnType("real");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("Grades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e25c7423-5a53-4c27-81d0-917b5e10b8e7"),
                            AverageGrade = 0f,
                            DefaultValue = false,
                            Grades = "[89,100]",
                            GroupId = new Guid("2d78dc28-25c1-4e52-a08d-5a78a8f81c5d"),
                            LastName = "Лайтер",
                            Name = "Ярина",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        },
                        new
                        {
                            Id = new Guid("fbcbb0a9-85e0-45a3-93c8-b1a057e4f062"),
                            AverageGrade = 0f,
                            DefaultValue = false,
                            Grades = "[79,95]",
                            GroupId = new Guid("69f6d9a2-3a21-48f0-aa59-2bc982b367c3"),
                            LastName = "Пильпака",
                            Name = "Альона",
                            SpecialtyId = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2")
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lecturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9e449e0-d8a1-4bfa-8dc5-3ec0d8b9a68d"),
                            Abbreviation = "ПР",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Клебан Ю.В.",
                            Name = "Програмування на С#"
                        },
                        new
                        {
                            Id = new Guid("7b96a6c2-8469-4d58-a3f0-bbb1aef4907c"),
                            Abbreviation = "БД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Коцюк Ю.А.",
                            Name = "Бази Даних"
                        },
                        new
                        {
                            Id = new Guid("dc57160e-d37e-4d81-a048-245106c4854b"),
                            Abbreviation = "АД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Жуковський В.В.",
                            Name = "Алгоритми даних"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.SubjectStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<float>("Grade")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.ToTable("SubjectStudent");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3b12b51e-54ad-461c-bdca-2bcbf03010e6"),
                            DefaultValue = false,
                            Grade = 89f,
                            StudentId = new Guid("e25c7423-5a53-4c27-81d0-917b5e10b8e7"),
                            SubjectId = new Guid("a9e449e0-d8a1-4bfa-8dc5-3ec0d8b9a68d")
                        },
                        new
                        {
                            Id = new Guid("e0bfe523-d69f-47e5-99c9-b6a4c074b097"),
                            DefaultValue = false,
                            Grade = 100f,
                            StudentId = new Guid("e25c7423-5a53-4c27-81d0-917b5e10b8e7"),
                            SubjectId = new Guid("7b96a6c2-8469-4d58-a3f0-bbb1aef4907c")
                        },
                        new
                        {
                            Id = new Guid("cebaafd2-1800-4f23-9b0e-d0fca405dbae"),
                            DefaultValue = false,
                            Grade = 96f,
                            StudentId = new Guid("fbcbb0a9-85e0-45a3-93c8-b1a057e4f062"),
                            SubjectId = new Guid("dc57160e-d37e-4d81-a048-245106c4854b")
                        });
                });

            modelBuilder.Entity("Grades.Persistence.Repositories.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef3018ed-0da7-4c69-8bc2-2f69361d95ac"),
                            DefaultValue = false,
                            Number = 1,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = new Guid("1854ba4d-f1f9-4155-a4f4-fb7eca90b11f"),
                            DefaultValue = false,
                            Number = 2,
                            StartYear = 2022
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "1eeef829-f30f-4f3f-b932-4fa9893585ed",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "6bc9e281-ea5a-4a42-b546-8970dc2f1181",
                            Name = "Faculty",
                            NormalizedName = "FACULTY"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "cfd51137-0220-4e2a-8544-0306797dcd3f",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Student", b =>
                {
                    b.HasOne("Grades.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.SubjectStudent", b =>
                {
                    b.HasOne("Grades.Domain.Entities.Student", "Student")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.Subject", "Subject")
                        .WithMany("SubjectStudents")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Grades.Domain.Entities.Student", b =>
                {
                    b.Navigation("SubjectStudents");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.Navigation("SubjectStudents");
                });
#pragma warning restore 612, 618
        }
    }
}
