// <auto-generated />
using System;
using Grades.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grades.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227001008_InitFaculty")]
    partial class InitFaculty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grades.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            Abbreviation = "A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9782eeb9-6315-4aaa-854c-66f0c95b21a2",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF7t5bwnRJ6mTsl6SoyWIonn7+MMUSm9Bq3qgjvHV26UTpkUwRhFTOp9TzYmnMxhkQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c6997e68-296b-4ddb-9b2e-8fbbefc872c9",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Abbreviation = "EC",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "695afa48-d95c-4ea3-b062-b00250195b07",
                            Email = "economy@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Economy Faculty",
                            NormalizedEmail = "ECONOMY@GMAIL.COM",
                            NormalizedUserName = "ECONOMY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEs/bRH85aDa58K5uJuHzVIPVe+36/3lLOR8FsktJzcnVogXaRanhODLo47qTvExPg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5979f356-c58b-427b-ad04-ecf646a4235a",
                            TwoFactorEnabled = false,
                            UserName = "economy@gmail.com"
                        },
                        new
                        {
                            Id = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            Abbreviation = "LF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6eeb7a91-bcf2-40b8-a6b4-27bbf7e5c468",
                            Email = "law@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Law Faculty",
                            NormalizedEmail = "LAW@GMAIL.COM",
                            NormalizedUserName = "LAW@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECEvi8DtuZjxjY9xYCmtl36AsjTbhcEgsG8lriMiaRLqjIFWESBD0obXKi/THjlkgg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c7a23cdf-de03-4ea2-a09e-91d72ed08ae2",
                            TwoFactorEnabled = false,
                            UserName = "law@gmail.com"
                        },
                        new
                        {
                            Id = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            Abbreviation = "U",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7036d82a-8460-4698-ae58-979f27894257",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMN9Xw02kW+Cgmcx8EQH4CpwUTqlFWPGcAKMqHJILfc4imaPjyOkzQNGVr9FSTlh2w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2b58baa3-ab70-4426-8002-a694682edc1c",
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5c3bad37-9e37-4b93-bcfb-e6e190c47e42"),
                            Abbreviation = "F1",
                            DefaultValue = false,
                            Name = "Faculty 1"
                        },
                        new
                        {
                            Id = new Guid("08001d7a-f6b5-48ea-be58-fbf213025393"),
                            Abbreviation = "F2",
                            DefaultValue = false,
                            Name = "Faculty 2"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc0df677-74bb-4099-b868-eea8f9c76380"),
                            AdmissionYear = 2021,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 1
                        },
                        new
                        {
                            Id = new Guid("6baa21a2-8095-4884-8ff0-3358260bfb42"),
                            AdmissionYear = 2020,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "ЕК",
                            SpecialtyId = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            SubgroupNumber = 2
                        },
                        new
                        {
                            Id = new Guid("82927e12-f832-424d-bbb1-8978c94c897f"),
                            AdmissionYear = 2022,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 2
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            Code = "122",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Комп'ютерні науки"
                        },
                        new
                        {
                            Id = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            Code = "051",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Економіка"
                        },
                        new
                        {
                            Id = new Guid("b6d2cb2f-8c5a-4ff4-98b2-728c3d0f2c8e"),
                            Code = "075",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Маркетинг"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lecturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b48e854-46f6-440c-985f-c6088fefe905"),
                            Abbreviation = "ПР",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Клебан Ю.В.",
                            Name = "Програмування на С#",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        },
                        new
                        {
                            Id = new Guid("c949df6e-a06b-4005-b474-5d52055d8a67"),
                            Abbreviation = "БД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Коцюк Ю.А.",
                            Name = "Бази Даних",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        },
                        new
                        {
                            Id = new Guid("5986491c-d802-42a3-be59-46e2028040e4"),
                            Abbreviation = "АД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Жуковський В.В.",
                            Name = "Алгоритми даних",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        });
                });

            modelBuilder.Entity("Grades.Persistence.Repositories.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f74ebb34-4afb-406a-b2a2-6cf1e6bbce06"),
                            DefaultValue = false,
                            Number = 1,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = new Guid("d41b5c42-7e20-4efe-98a8-b6d8407fbb6e"),
                            DefaultValue = false,
                            Number = 2,
                            StartYear = 2022
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "01d141fe-537d-46a7-824e-e33d2f9f1f03",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "e497c9ef-886a-4c9a-b873-39a6c35127fb",
                            Name = "Faculty",
                            NormalizedName = "FACULTY"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "90c3dd3b-e8c4-4285-96f7-e82d078acb7e",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
