// <auto-generated />
using System;
using Grades.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grades.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240227011049_InitFaculty2")]
    partial class InitFaculty2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grades.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            Abbreviation = "A",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5cabbe1d-01b9-4a43-8f46-d6661b2062a0",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMbVhC9q+eJwulMepHSiHRtwAePm21xBerJAb+7lGt/H8YiR6MdI2++PHd6dECVgdA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8af9605c-07d5-4a8c-a68b-86d6a8943c3f",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Abbreviation = "EC",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ddda02ed-230c-4a5f-8ab0-c4e4d06260b8",
                            Email = "economy@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Economy Faculty",
                            NormalizedEmail = "ECONOMY@GMAIL.COM",
                            NormalizedUserName = "ECONOMY@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELMzqY7dn9kYwrSCgTLUqc6WDQ1UAxpQAWZtgeo57XpIcrNSvZXqlsEL19EOpK+hvg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0c8e7094-8aad-4304-ac46-b42b9887925f",
                            TwoFactorEnabled = false,
                            UserName = "economy@gmail.com"
                        },
                        new
                        {
                            Id = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            Abbreviation = "LF",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "90bf3aa0-3933-4e59-8d5e-f86cac37a8e0",
                            Email = "law@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Law Faculty",
                            NormalizedEmail = "LAW@GMAIL.COM",
                            NormalizedUserName = "LAW@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHBT1H+mYLqiKteoTIGnbSOAkP6dHcNSwRsOQCOYFuXObR2YLC3vxqfkGzwISSEK5w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1eae1b2f-4dee-4e84-86a9-09d676f2602c",
                            TwoFactorEnabled = false,
                            UserName = "law@gmail.com"
                        },
                        new
                        {
                            Id = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            Abbreviation = "U",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dcfb0cf-3a08-4621-817c-9e458ff83278",
                            Email = "user@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "User",
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKhIQy1vDyT59VtK4TdYAOXaSfxILE2sdVhst+2lJWwbOmiZKg0IabByWtOiOjegaw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06f424cd-6ec8-4f54-84ca-427da05e59ff",
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dbd59de2-3bc1-4bd7-a0af-46bfedc5f0dc"),
                            Abbreviation = "F1",
                            DefaultValue = false,
                            Name = "Faculty 1"
                        },
                        new
                        {
                            Id = new Guid("c221ac94-157f-4ee1-b053-4bf9f0b0067a"),
                            Abbreviation = "F2",
                            DefaultValue = false,
                            Name = "Faculty 2"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubgroupNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Group");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67583a96-d014-4b7e-b7e7-423ce0c489cc"),
                            AdmissionYear = 2021,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 1
                        },
                        new
                        {
                            Id = new Guid("384c3d4d-ecc5-4d5a-96cd-fce5f241c8dd"),
                            AdmissionYear = 2020,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "ЕК",
                            SpecialtyId = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            SubgroupNumber = 2
                        },
                        new
                        {
                            Id = new Guid("cce0212b-fbaf-4c87-8c46-3f476576256a"),
                            AdmissionYear = 2022,
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            GroupCode = "КН",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            SubgroupNumber = 2
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.ToTable("Specialty");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc"),
                            Code = "122",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Комп'ютерні науки"
                        },
                        new
                        {
                            Id = new Guid("aee59fc8-92f4-4bb7-a0a7-4f812f74a4c2"),
                            Code = "051",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Економіка"
                        },
                        new
                        {
                            Id = new Guid("b6d2cb2f-8c5a-4ff4-98b2-728c3d0f2c8e"),
                            Code = "075",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Name = "Маркетинг"
                        });
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<string>("FacultyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Lecturer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SpecialtyId");

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = new Guid("35e62777-dc20-402c-b9d6-82a300d645c4"),
                            Abbreviation = "ПР",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Клебан Ю.В.",
                            Name = "Програмування на С#",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        },
                        new
                        {
                            Id = new Guid("172e5a52-df51-4fb0-b062-bd2864185d8e"),
                            Abbreviation = "БД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Коцюк Ю.А.",
                            Name = "Бази Даних",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        },
                        new
                        {
                            Id = new Guid("2050ae9f-d8dc-4f30-ae8d-d153cda3e44d"),
                            Abbreviation = "АД",
                            DefaultValue = false,
                            FacultyId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            Lecturer = "Жуковський В.В.",
                            Name = "Алгоритми даних",
                            SpecialtyId = new Guid("e0d30663-5fc2-4aa4-bd12-9f325db791dc")
                        });
                });

            modelBuilder.Entity("Grades.Persistence.Repositories.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultValue")
                        .HasColumnType("bit");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a90adf2d-7c5d-4300-b5dc-2735bd84654e"),
                            DefaultValue = false,
                            Number = 1,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = new Guid("0e8e3daa-c991-4762-992b-3c836b91f196"),
                            DefaultValue = false,
                            Number = 2,
                            StartYear = 2022
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "024af808-9b34-4839-85b6-adda7b042ac4",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "d8021dcd-e854-4618-a11a-2dd00450899f",
                            Name = "Faculty",
                            NormalizedName = "FACULTY"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "bdcb3ed4-f0db-4fd9-8585-cbd4707219bf",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "49b754b0-8831-4b1a-a44f-8e18a0c2578e",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "edb4f3c1-cf69-4b07-aafb-915d6d58f23d",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "7e7b3d2d-9a90-4f90-aa5f-2c33d830cf45",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "c8b05623-d42b-4a9f-947e-dcd54538ee1d",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Grades.Domain.Entities.Group", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Grades.Domain.Entities.Subject", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", "Faculty")
                        .WithMany()
                        .HasForeignKey("FacultyId");

                    b.HasOne("Grades.Domain.Entities.Specialty", "Specialty")
                        .WithMany()
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Grades.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
