// <auto-generated />
using System;
using Grades.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Grades.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Grades.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dd40723-c6d6-45fa-8853-7f1568968a98"),
                            Abbreviation = "F1",
                            Name = "Faculty 1"
                        },
                        new
                        {
                            Id = new Guid("5414e568-334f-4bad-adaa-eca57f177b79"),
                            Abbreviation = "F2",
                            Name = "Faculty 2"
                        });
                });

            modelBuilder.Entity("Grades.Persistence.Repositories.Semester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Semesters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9b563ca-c22a-493f-b2f7-3d774452d240"),
                            Number = 1,
                            StartYear = 2022
                        },
                        new
                        {
                            Id = new Guid("98ef7c6b-e74b-4548-837a-446c88d0bd23"),
                            Number = 2,
                            StartYear = 2022
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
