// <auto-generated />
using System;
using GradesApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GradesApp.Infrastructure.Migrations
{
    [DbContext(typeof(GradesAppDbContext))]
    [Migration("20240724094519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GradesApp.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5f6d5df-7be0-4992-a1e7-5e7d2289650f"),
                            FullName = "John Doe",
                            Speciality = "Computer Science",
                            UserId = new Guid("5e4a1dee-ea7a-4dbc-a8e5-0c8f99c95496"),
                            Year = 2
                        },
                        new
                        {
                            Id = new Guid("6fad6572-d860-41e1-b201-faf3739330c9"),
                            FullName = "Jane Smith",
                            Speciality = "Mathematics",
                            UserId = new Guid("0254284e-def0-4daa-a221-0ac1dc48616c"),
                            Year = 3
                        });
                });

            modelBuilder.Entity("GradesApp.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e4a1dee-ea7a-4dbc-a8e5-0c8f99c95496"),
                            Email = "john@example.com",
                            PasswordHash = "$2a$11$jgAEEJLsavkSIu.YtVWv9.DCQFq2IonZ9ScMc5X4GYoxg1F81HNmW",
                            Role = "Student",
                            Username = "john_doe"
                        },
                        new
                        {
                            Id = new Guid("0254284e-def0-4daa-a221-0ac1dc48616c"),
                            Email = "jane@example.com",
                            PasswordHash = "$2a$11$d1j2dIPr2NVeg3O3qDE/8.NbHCGhzUMtXdUqPt9cWWvxgfHu590CG",
                            Role = "Student",
                            Username = "jane_smith"
                        });
                });

            modelBuilder.Entity("GradesApp.Domain.Entities.Student", b =>
                {
                    b.HasOne("GradesApp.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("GradesApp.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GradesApp.Domain.Entities.User", b =>
                {
                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
